import { useState } from 'react';

export default function DockerignoreGenerator() {
  const [output, setOutput] = useState('');
  const [copied, setCopied] = useState(false);
  const [selected, setSelected] = useState<Record<string, boolean>>({
    // Dependencies
    node_modules: true,
    vendor: true,
    bower_components: true,
    // Build outputs
    dist: true,
    build: true,
    out: true,
    target: true,
    bin: true,
    obj: true,
    // IDE/Editor
    '.idea': true,
    '.vscode': true,
    '*.swp': true,
    '*.swo': true,
    '*~': true,
    '.DS_Store': true,
    'Thumbs.db': true,
    // Logs
    '*.log': true,
    'npm-debug.log*': true,
    'yarn-debug.log*': true,
    'yarn-error.log*': true,
    // Test/coverage
    coverage: true,
    '.nyc_output': true,
    '.pytest_cache': true,
    '.coverage': true,
    // Environment
    '.env': true,
    '.env.local': true,
    '.env.*.local': true,
    // Docker
    'Dockerfile*': false,
    'docker-compose*.yml': false,
    '.dockerignore': false,
    // Git
    '.git': true,
    '.gitignore': false,
    // Misc
    '*.pem': true,
    '*.key': true,
    '*.crt': true,
  });

  const categories = {
    'Dependencies': ['node_modules', 'vendor', 'bower_components'],
    'Build Outputs': ['dist', 'build', 'out', 'target', 'bin', 'obj'],
    'IDE / Editor': ['.idea', '.vscode', '*.swp', '*.swo', '*~', '.DS_Store', 'Thumbs.db'],
    'Logs': ['*.log', 'npm-debug.log*', 'yarn-debug.log*', 'yarn-error.log*'],
    'Test / Coverage': ['coverage', '.nyc_output', '.pytest_cache', '.coverage'],
    'Environment': ['.env', '.env.local', '.env.*.local'],
    'Docker': ['Dockerfile*', 'docker-compose*.yml', '.dockerignore'],
    'Git': ['.git', '.gitignore'],
    'Secrets / Certs': ['*.pem', '*.key', '*.crt'],
  };

  const generate = () => {
    let content = '# Generated by ntools dockerignore-generator\n';
    content += '# https://github.com/ntools\n\n';
    
    Object.entries(categories).forEach(([cat, items]) => {
      content += `# ${cat}\n`;
      items.forEach(item => {
        if (selected[item]) {
          content += `${item}\n`;
        }
      });
      content += '\n';
    });

    // Add custom patterns
    content += '# Custom patterns (add your own)\n';
    content += '# \n';
    
    setOutput(content);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const download = () => {
    const blob = new Blob([output], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = '.dockerignore';
    a.click();
    URL.revokeObjectURL(url);
  };

  const toggleAll = (category: string, value: boolean) => {
    categories[category as keyof typeof categories].forEach(item => {
      setSelected(prev => ({ ...prev, [item]: value }));
    });
  };

  // Generate on mount
  if (!output) generate();

  return (
    <div className="tool-container">
      <div className="tool-header">
        <h2>.dockerignore Generator</h2>
        <p className="tool-desc">Generate a comprehensive .dockerignore file for your Docker builds. Select patterns to exclude from the build context.</p>
      </div>

      <div className="dockerignore-layout">
        <div className="options-panel">
          {Object.entries(categories).map(([category, items]) => (
            <div key={category} className="category-section">
              <div className="category-header">
                <h3>{category}</h3>
                <div className="category-actions">
                  <button className="btn-sm" onClick={() => toggleAll(category, true)}>All</button>
                  <button className="btn-sm" onClick={() => toggleAll(category, false)}>None</button>
                </div>
              </div>
              <div className="patterns-grid">
                {items.map(item => (
                  <label key={item} className="pattern-checkbox">
                    <input
                      type="checkbox"
                      checked={selected[item]}
                      onChange={e => setSelected(prev => ({ ...prev, [item]: e.target.checked }))}
                    />
                    <code>{item}</code>
                  </label>
                ))}
              </div>
            </div>
          ))}

          <div className="custom-patterns">
            <h3>Custom Patterns</h3>
            <p className="hint">Add your own patterns (one per line)</p>
            <textarea
              className="custom-input"
              placeholder="# e.g.\n# *.tmp\n# secret/\n# local-config/"
              rows={4}
            />
          </div>

          <div className="actions">
            <button className="btn-primary" onClick={generate}>Generate</button>
            <button className="btn-secondary" onClick={copyToClipboard} disabled={!output}>
              {copied ? '✓ Copied!' : 'Copy to Clipboard'}
            </button>
            <button className="btn-secondary" onClick={download} disabled={!output}>
              Download .dockerignore
            </button>
          </div>
        </div>

        <div className="preview-panel">
          <div className="preview-header">
            <h3>Preview</h3>
            <span className="line-count">{output.split('\n').length} lines</span>
          </div>
          <pre className="preview-output"><code>{output || 'Click Generate to preview'}</code></pre>
        </div>
      </div>
    </div>
  );
}